/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package viw;

import java.awt.Color;
import java.awt.Font;
import Dao.daoclientes;
import java.util.ArrayList;
import java.util.List;
import model.modelclientes;
import Controler.controlerclientes;
import javax.swing.JOptionPane;
import model.Modelrecebiveis;
import Controler.Controlerrecebiveis;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;
/**
 *
 * @author ruan
 */
public class Contasreceber extends javax.swing.JFrame {
modelclientes clientes = new modelclientes();
controlerclientes clientescontroler = new controlerclientes();
Modelrecebiveis recebiveis = new Modelrecebiveis();
Controlerrecebiveis controlerrecebiveis = new Controlerrecebiveis();
List<Modelrecebiveis> listarecebiveltelacadastro = new ArrayList<>();
private boolean carregandoCombo = true;
    /**
     * Creates new form Contasreceber
     */
    public Contasreceber() {
        initComponents();
        preencherDataEmissaoAutomatica();
        setLocationRelativeTo(this);
        designtabelacontasreceber();
        jSpinner1.addChangeListener(new ChangeListener() {
        public void stateChanged(ChangeEvent e) {
        gerarParcelas();//gera parcelas automaticamente ao selecionar um numero no spinner e mostrar na tabela
    }
        });
       
       
    }
    
    private void gerarParcelas() {
        try {
        double valorTotal = Double.parseDouble(valor.getText());
        int numeroParcelas = (Integer) jSpinner1.getValue();
        String vencimentoStr = vencimento.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date dataVencimento = sdf.parse(vencimentoStr);
        double valorParcela = valorTotal / numeroParcelas;

        DefaultTableModel modelo = (DefaultTableModel) tabelarecebivelcadastro.getModel();
        modelo.setColumnIdentifiers(new Object[]{"Código", "Parcela", "Vencimento", "Valor total"});
        modelo.setRowCount(0);

        Calendar cal = Calendar.getInstance();
        cal.setTime(dataVencimento);

        for (int i = 1; i <= numeroParcelas; i++) {
            String parcela = i + "/" + numeroParcelas;
            String venc = sdf.format(cal.getTime());
            modelo.addRow(new Object[]{i, parcela, venc, String.format("R$ %.2f", valorParcela)});
            cal.add(Calendar.MONTH, 1);
        }

        modelo.fireTableDataChanged();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao gerar parcelas: " + e.getMessage());
        e.printStackTrace(); // opcional para ver no console
    }
}
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        gerarconta = new javax.swing.JButton();
        Limparformulario = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rua = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        cpf = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        telefone = new javax.swing.JFormattedTextField();
        origem = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dataemissao = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        vencimento = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelarecebivelcadastro = new javax.swing.JTable();
        combocliente = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        codigo = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        descricaovenda = new javax.swing.JFormattedTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        chavecliente = new javax.swing.JFormattedTextField();
        valor = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Contas Para Receber");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(150, 150, 150))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        gerarconta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        gerarconta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/receber (1).png"))); // NOI18N
        gerarconta.setText("Gerar Conta");
        gerarconta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarcontaActionPerformed(evt);
            }
        });

        Limparformulario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Limparformulario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar (1).png"))); // NOI18N
        Limparformulario.setText("Cancelar");
        Limparformulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparformularioActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/po (1).png"))); // NOI18N
        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair (1).png"))); // NOI18N
        jButton4.setText("Sair");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(gerarconta, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Limparformulario, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gerarconta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Limparformulario, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Pesquisar Cliente(Nome do Cliente A-Z):");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("rua");

        rua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("CPF:");

        cpf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Telefone:");

        telefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneActionPerformed(evt);
            }
        });

        origem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        origem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Origem:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Valor Total(R$):");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Data de Emissão:");

        dataemissao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            dataemissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataemissao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Vencimento:");

        vencimento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            vencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        vencimento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Numero de Parcelas:");

        tabelarecebivelcadastro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabelarecebivelcadastro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Parcela", "Vencimento", "Valor Parcela"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelarecebivelcadastro.setFocusable(false);
        tabelarecebivelcadastro.setRowHeight(25);
        tabelarecebivelcadastro.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tabelarecebivelcadastro.setShowVerticalLines(false);
        tabelarecebivelcadastro.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelarecebivelcadastro);

        combocliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combocliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        combocliente.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                comboclienteAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        combocliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboclienteActionPerformed(evt);
            }
        });
        combocliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                comboclienteKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Código:");

        codigo.setEditable(false);
        codigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        codigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Descrição da Venda:");

        descricaovenda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        descricaovenda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jSpinner1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSpinner1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Id Cliente:");

        chavecliente.setEditable(false);
        chavecliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chavecliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chavecliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chaveclienteActionPerformed(evt);
            }
        });

        valor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        valor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(combocliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(1, 1, 1))
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(chavecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(rua, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(origem)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(dataemissao, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(descricaovenda, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(telefone)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valor)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(combocliente, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(chavecliente)
                    .addComponent(codigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rua, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valor))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(origem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descricaovenda, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dataemissao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(vencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void designtabelacontasreceber(){
        tabelarecebivelcadastro.getColumnModel().getColumn(0).setPreferredWidth(60);   // Código
tabelarecebivelcadastro.getColumnModel().getColumn(1).setPreferredWidth(270);  // Parcela
tabelarecebivelcadastro.getColumnModel().getColumn(2).setPreferredWidth(100);  // Vencimento
tabelarecebivelcadastro.getColumnModel().getColumn(3).setPreferredWidth(100); 
        tabelarecebivelcadastro.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tabelarecebivelcadastro.getTableHeader().setOpaque(false);
        tabelarecebivelcadastro.getTableHeader().setBackground(new Color(32, 136, 203));
        tabelarecebivelcadastro.getTableHeader().setForeground( new Color(255,255,255));
        tabelarecebivelcadastro.setRowHeight(25);
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneActionPerformed

    private void comboclienteAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_comboclienteAncestorAdded
      
        carregandoCombo = true;
        daoclientes clientescombo = new daoclientes();
        List<modelclientes> listacliente = clientescombo.Carregarclientetabelavizualizar();
        combocliente.removeAll();
        
        for(modelclientes c: listacliente){
           
            combocliente.addItem(c);
        }
         carregandoCombo = false;
    }//GEN-LAST:event_comboclienteAncestorAdded

    private void comboclienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboclienteKeyReleased
       
    }//GEN-LAST:event_comboclienteKeyReleased

    private void comboclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboclienteActionPerformed
       if (carregandoCombo) return;
        modelclientes clienteSelecionado = (modelclientes) combocliente.getSelectedItem();
    if (clienteSelecionado != null) {
        String nomevariavel = clienteSelecionado.getNome(); // pega o nome
        clientes = clientescontroler.carregarDadosclientes(nomevariavel);
        
        if (clientes != null) {
            Limpar();
            chavecliente.setText(String.valueOf(clientes.getCodigo()));
            rua.setText(clientes.getRua());
            cpf.setText(clientes.getCpf());
            telefone.setText(clientes.getTelefone());
        } else {
            JOptionPane.showMessageDialog(null, "Cliente não encontrado no banco de dados.");
        }
    }
    }//GEN-LAST:event_comboclienteActionPerformed

    private void chaveclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chaveclienteActionPerformed
       
    }//GEN-LAST:event_chaveclienteActionPerformed

    private void gerarcontaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarcontaActionPerformed
        recebiveis = new Modelrecebiveis();
        if (chavecliente.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "'Escolha um cliente em 'Pesquisar Cliente'");
            return;
        }
         else {
            recebiveis.setChavecliente(Integer.parseInt(chavecliente.getText()));
            
        }
        recebiveis.setEndereco(rua.getText());
        recebiveis.setCpf(cpf.getText());
        recebiveis.setTelefone(telefone.getText());
        recebiveis.setOrigem(origem.getText());
        String descricao = descricaovenda.getText().trim();
        if (descricao.isEmpty()) {
        descricao = "Compra não identificada";
        recebiveis.setDescricao(descricao);
        }
        else{
            recebiveis.setDescricao(descricaovenda.getText());
        }
        if (valor.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "'Digite um Valor para Salvar a Conta'");
            return;
        }
        else {
            recebiveis.setValor(Double.parseDouble(valor.getText()));
        }
        recebiveis.setEmissaao(dataemissao.getText());
        String venc = vencimento.getText().replaceAll("[^0-9]", ""); 
        if (venc.isEmpty() || venc.length() < 8) {
        JOptionPane.showMessageDialog(null, "Digite uma data de vencimento válida!");
        return;
        } else {
        recebiveis.setVencimento(vencimento.getText());
        }
        int valor = (int) jSpinner1.getValue();
        if(valor <=0){
            JOptionPane.showMessageDialog(null, "Escolha um numero no campo: 'Numero de Parcelas' Caso seja uma conta sem parcelamento Escolha o numero 1 para conta única");
            return;
        }
        else{
             recebiveis.setParcelas(Integer.parseInt(jSpinner1.getValue().toString()));
        }
        // Antes de salvar, vamos verificar os dados que estão no objeto
System.out.println("Dados antes de salvar:");
System.out.println("Cliente: " + recebiveis.getChavecliente());
System.out.println("Rua: " + recebiveis.getEndereco());
System.out.println("CPF: " + recebiveis.getCpf());
System.out.println("Telefone: " + recebiveis.getTelefone());
System.out.println("Origem: " + recebiveis.getOrigem());
System.out.println("Descrição: " + recebiveis.getDescricao());
System.out.println("Valor: " + recebiveis.getValor());
System.out.println("Emissão: " + recebiveis.getEmissaao());
System.out.println("Vencimento: " + recebiveis.getVencimento());
System.out.println("Parcelas: " + recebiveis.getParcelas());
         if (controlerrecebiveis.Salvarconta(recebiveis)) {
            JOptionPane.showMessageDialog(null, "Conta cadastrado com Sucesso!");
            //Carregarcontas();
            Limpar();
           
        } else {
            JOptionPane.showMessageDialog(null, "Conta Não cadastrada!");
             Limpar();
        }
        
    }//GEN-LAST:event_gerarcontaActionPerformed
    private void Carregarcontas(){
        int codigoCliente = Integer.parseInt(chavecliente.getText()); 
        listarecebiveltelacadastro = controlerrecebiveis.cadastrorecebivel(codigoCliente);
        DefaultTableModel modelo = (DefaultTableModel) tabelarecebivelcadastro.getModel();
        modelo.setNumRows(0);
        NumberFormat formatoMoeda = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
        for (int i = 0; i <  listarecebiveltelacadastro.size(); i++) {
             modelo.addRow(new Object[]{
                listarecebiveltelacadastro.get(i).getCod(),
                listarecebiveltelacadastro.get(i).getDescricao(), 
                listarecebiveltelacadastro.get(i).getVencimento(),
                formatoMoeda.format(listarecebiveltelacadastro.get(i).getValor())
            });
        }
    }
    
    
    
    private void preencherDataEmissaoAutomatica() {
    SimpleDateFormat formatoData = new SimpleDateFormat("dd/MM/yyyy");
    String dataFormatada = formatoData.format(new Date());
    dataemissao.setText(dataFormatada);  // Aqui é 100% compatível com a máscara
}
   
    

 
    
    

    
    private void LimparformularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparformularioActionPerformed
        Limpar();
    }//GEN-LAST:event_LimparformularioActionPerformed
    public void Limpar(){
        jSpinner1.setValue(0);
        chavecliente.setText("");
        rua.setText("");
        cpf.setValue(null); 
        cpf.setFocusLostBehavior(cpf.COMMIT);
        telefone.setValue(null); 
        telefone.setFocusLostBehavior(telefone.COMMIT);
        origem.setText("");
        descricaovenda.setText("");
        valor.setValue(null);
        valor.setFocusLostBehavior(valor.COMMIT);
        vencimento.setValue(null);
        vencimento.setFocusLostBehavior(vencimento.COMMIT);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contasreceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contasreceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contasreceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contasreceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contasreceber().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limparformulario;
    private javax.swing.JFormattedTextField chavecliente;
    private javax.swing.JFormattedTextField codigo;
    private javax.swing.JComboBox combocliente;
    private javax.swing.JFormattedTextField cpf;
    private javax.swing.JFormattedTextField dataemissao;
    private javax.swing.JFormattedTextField descricaovenda;
    private javax.swing.JButton gerarconta;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JFormattedTextField origem;
    private javax.swing.JFormattedTextField rua;
    private javax.swing.JTable tabelarecebivelcadastro;
    private javax.swing.JFormattedTextField telefone;
    private javax.swing.JFormattedTextField valor;
    private javax.swing.JFormattedTextField vencimento;
    // End of variables declaration//GEN-END:variables

    public void preechercamposconta(Modelrecebiveis recebieisexibição) {
    codigo.setText(String.valueOf(recebieisexibição.getCod()));
    chavecliente.setText(String.valueOf(recebieisexibição.getChavecliente()));
    rua.setText(recebieisexibição.getEndereco());
    cpf.setText(recebieisexibição.getCpf());
    telefone.setText(recebieisexibição.getTelefone());
    origem.setText(recebieisexibição.getOrigem());
    descricaovenda.setText(recebieisexibição.getDescricao());
    valor.setText(String.valueOf(recebieisexibição.getValor()));
    dataemissao.setText(recebieisexibição.getEmissaao());
    vencimento.setText(recebieisexibição.getVencimento());

     for (int i = 0; i < combocliente.getItemCount(); i++) {//primeira alteração para setar um cliente na combobox pelo outro jframe 
        modelclientes cliente = (modelclientes) combocliente.getItemAt(i);
        if (cliente.getNome().equalsIgnoreCase(recebieisexibição.getNomecliente())) {
            combocliente.setSelectedIndex(i);
            break;
        }
    }
   
    }
    
    public void carregarClientesCombo() {//terceira alteração para setar um cliente na combobox pelo outro jframe 
    combocliente.removeAllItems();
    daoclientes clientescombo = new daoclientes();
    List<modelclientes> lista = clientescombo.Carregarclientetabelavizualizar();
    for (modelclientes c : lista) {
        combocliente.addItem(c);
    }
}

    public void selecaodeconta(List<Modelrecebiveis> Selecaocontas) {
        DefaultTableModel modelo = (DefaultTableModel) tabelarecebivelcadastro.getModel();
        modelo.setNumRows(0);
        NumberFormat formatoMoeda = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
        for (int i = 0; i < Selecaocontas.size(); i++) {
            modelo.addRow(new Object[]{
                Selecaocontas.get(i).getCod(),
                Selecaocontas.get(i).getDescricao(),
                Selecaocontas.get(i).getVencimento(),
                formatoMoeda.format(Selecaocontas.get(i).getValor()), 
            });
        }
    }
}
